#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from handeye_dashboard.plugin import HandEyeCalibration
plugin = 'handeye_dashboard.handeye_calibration.HandEyeCalibration'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
