pose_estimation:
    ros__parameters:
        pattern: CHARUCO
        image_topic: /table/camera/color/image_raw
        camera_info_topic: /table/camera/color/camera_info
        publish_image_topic: /image/detected
        width: 5
        height: 7
        dictionary: DICT_6X6_250
        charuco_board_marker_size: 0.022
        charuco_board_square_size: 0.037